### ISSUE TITLE
`initialize': No such file or directory error

### ISSUE THREAD

**Issue by chenweiyj** [amatsuda/kaminari_themes#67]
I cannot get the theme view when I type
> rails g kaminari:views bootstrap3

It shows me:

```
/Users/chenwei/.rvm/gems/ruby-2.4.0/gems/kaminari-core-1.0.1/lib/generators/kaminari/views_generator.rb:114:in `initialize': No such file or directory @ rb_sysopen - https://api.github.com/repos/amatsuda/kaminari_themes/git/refs/heads/master (Errno::ENOENT)
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/kaminari-core-1.0.1/lib/generators/kaminari/views_generator.rb:114:in `open'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/kaminari-core-1.0.1/lib/generators/kaminari/views_generator.rb:114:in `get_files_in_master'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/kaminari-core-1.0.1/lib/generators/kaminari/views_generator.rb:40:in `themes'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/kaminari-core-1.0.1/lib/generators/kaminari/views_generator.rb:29:in `copy_or_fetch'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/generators.rb:269:in `invoke'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/commands/generate/generate_command.rb:24:in `perform'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/command/base.rb:63:in `perform'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/command.rb:44:in `invoke'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/railties-5.1.3/lib/rails/commands.rb:16:in `<top (required)>'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:292:in `require'
	from /Users/chenwei/Documents/workspace/tempruby/chorder/bin/rails:9:in `<top (required)>'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `block in load'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/chenwei/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.3/lib/active_support/dependencies.rb:286:in `load'
	from /Users/chenwei/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/chenwei/.rvm/rubies/ruby-2.4.0/lib/ruby/site_ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

**Comment by yuki24** [comment]
Thanks for reporting. We actually received the same bug report, and @jvsoares kindly [sent a pull request](https://github.com/kaminari/kaminari/pull/912) and fixed the issue. We will cut a new release soon. Thanks for your patience!

**Comment by efrapp** [comment]
Hi,
Was it resolve? I'm trying to use it but I get the same error.

**Comment by efrapp** [comment]
Sorry I was using the version 0.17.0. Now I'm using 1.1.1 and it is working ok.
