### ISSUE TITLE
Issue when trying to generate new view themes

### ISSUE THREAD

**Issue by IsolatePy** [amatsuda/kaminari_themes#74]
Hi
I have an issue when installing the theme on rails 6
for example `rails g kaminari:views github`

> raceback (most recent call last):
        17: from bin/rails:4:in `<main>'
        16: from bin/rails:4:in `require'
        15: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands.rb:18:in `<top (required)>'
        14: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/command.rb:46:in `invoke'
        13: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/command/base.rb:65:in `perform'
        12: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        11: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        10: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
         9: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/commands/generate/generate_command.rb:26:in `perform'
         8: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/generators.rb:276:in `invoke'
         7: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
         6: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:219:in `dispatch'
         5: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/group.rb:31:in `help'
         4: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/kaminari-0.16.3/lib/generators/kaminari/views_generator.rb:19:in `banner'
         3: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/kaminari-0.16.3/lib/generators/kaminari/views_generator.rb:39:in `themes'
         2: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/kaminari-0.16.3/lib/generators/kaminari/views_generator.rb:99:in `get_files_in_master'
         1: from C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/kaminari-0.16.3/lib/generators/kaminari/views_generator.rb:99:in `open'
C:/Ruby/Ruby26-x64/lib/ruby/gems/2.6.0/gems/kaminari-0.16.3/lib/generators/kaminari/views_generator.rb:99:in `initialize': Invalid argument @ rb_sysopen - https://api.github.com/repos/amatsuda/kaminari_themes/git/refs/heads/master (Errno::EINVAL)

**Comment by ognjenio** [comment]
I encountered this issue as well. Kaminari repo says it's fixed so it's probably a matter of versions we're running. I just copied the files from this repo. 

ref: https://github.com/kaminari/kaminari/issues/1047
